spring:
  application:
    name: spring-stream-kafka

  cloud:
    function:
      definition: news;createAlertKafkaEvent;deleteAlertKafkaEvent
    stream:
      default-binder: kafka
      kafka:
        streams:
          binder:
            brokers: 'localhost:9021'
            auto-create-topics: true
      bindings:
        news-in-0:
          destination: news
          content-type: application/json
          group: newsConsumerGroup
          consumer:
            concurrency: 5
        news-out-0:
          destination: news
          content-type: application/json
          producer:
            partition-key-expression: 'headers["partitionKey"]'
        createAlertKafkaEvent-in-0:
          destination: createAlertKafkaEvent
          content-type: application/json
          group: alertConsumerGroup
          consumer:
            concurrency: 5
        createAlertKafkaEvent-out-0:
          destination: createAlertKafkaEvent
          content-type: application/json
          producer:
            partition-key-expression: 'headers["partitionKey"]'
        deleteAlertKafkaEvent-in-0:
          destination: deleteAlertKafkaEvent
          content-type: application/json
          group: alertConsumerGroup
          consumer:
            concurrency: 5
        deleteAlertKafkaEvent-out-0:
          destination: deleteAlertKafkaEvent
          content-type: application/json
          producer:
            partition-key-expression: 'headers["partitionKey"]'


management.endpoints.web.exposure.include: beans,env,health,info,metrics,mappings
management.endpoint.health.show-details: always

logging:
  level:
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: WARN